### ISSUE TITLE
MVPリリース

### ISSUE THREAD

**Issue by g4rkk** [g4rkk/Buddhism#24]
## 各種情報
サービスの概要とMVPで検証する事柄：
このウェブサイトは、仏教に関する知識や教えを提供し、ユーザーが心の平安や自己成長を促進するための情報を得ることができるサービスです。簡単にアクセスできる教えや経典を含み、瞑想や日々の心の持ち方に役立つコンテンツを提供します。初心者から経験者まで、すべてのユーザーが仏教の教えを通じて心の安らぎを見つけられる場所です。

サービス名：仏教の世界

サービスURL：https://buddhismworld.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [✔] ユーザー登録機能
- [✔] ログイン機能
- [✔] パスワード変更機能
- [✔] メールアドレス変更機能
- [✔] プロフィール編集機能
- [✔] 瞑想時間の集計と可視化機能
- [✔] 瞑想ガイドの選択機能
- [✔] 経典のブックマーク機能
- [✔] 経典のアップロードとダウンロード機能

READMEのMVPレビュー時に実装予定だった機能が実装できています。

## READMEレビュー時から変更した機能
ブックマーク機能、瞑想時間の可視化機能を添えました。
本リリース向けて頑張ります。

## サービスイメージがわかるようなスクリーンショット等
<img width="1578" alt="截屏2024-10-15 01 57 56" src="https://github.com/user-attachments/assets/153ca653-661b-4b28-a7d3-c5b4f536f81c">
トップページです

---

<img width="1578" alt="截屏2024-10-15 01 58 14" src="https://github.com/user-attachments/assets/b56e195e-5b21-4563-9804-83ab2d8343f1">
瞑想の種類を選んで瞑想時間の記録機能です

---

<img width="1578" alt="截屏2024-10-15 01 58 52" src="https://github.com/user-attachments/assets/f13ea4d2-7766-4b4b-8e22-d755cf47e029">
時間はマイページで可視化されます。

---

<img width="1578" alt="截屏2024-10-15 01 58 43" src="https://github.com/user-attachments/assets/22126faf-ac43-4683-9f3e-ffdf6f289fb4">
マークした本は自分のブックマークに反応されます、ダウンロード可能です。

**Comment by Tsuchiya2** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
