### ISSUE TITLE
issueベースの開発

### ISSUE THREAD

**Issue by g4rkk** [g4rkk/Buddhism#5]
■Webアプリの概要
このウェブサイトは、仏教に関する知識や教えを提供し、ユーザーが心の平安や自己成長を促進するための情報を得ることができるサービスです。 簡単にアクセスできる教えや経典を含み、瞑想や日々の心の持ち方に役立つコンテンツを提供します。 初心者から経験者まで、すべてのユーザーが仏教の教えを通じて心の安らぎを見つけられる場所です。

■1週間辺りの開発に向けられる時間
- 1週間あたり：70時間

■ProjectsのURL
https://github.com/users/g4rkk/projects/1/views/1

■MVPリリースまで
- [ ] ユーザー登録機能
- [ ] ログイン機能
- [ ] パスワード変更機能
- [ ] メールアドレス変更機能
- [ ] 仏教に関する基本的な教えや経典の閲覧 
- [ ] 瞑想ガイドの提供

■MVP後
- [ ] 瞑想や学びを助けるリマインダー機能
- [ ] 仏教仲間探し機能
- [ ] 日本国内の仏教参拝マップ

■MVPレビュー依頼予定日
予定日：2024年 10月 15日

**Comment by ippei-shimizu** [comment]
対応ありがとうございます。
ストーリーポイントを確認したところ、4ポイント以上のカードが存在するのを確認しました。
カリキュラムにもありましたとおり、ストーリーポイント3以下になるように細かくissue化してください。
細かくissue化することで、不明瞭な箇所、明瞭な箇所が可視化されることに加えて、進捗を感じられながら開発を進めることができます。
対応の上、再提出操作をお願いいたします。

- [仏教の経典の閲覧機能（refile,refile-mini_magickファイルのアップロード）](https://github.com/users/g4rkk/projects/1/views/1?pane=issue&itemId=82975286)
- [瞑想ガイド機能](https://github.com/users/g4rkk/projects/1/views/1?pane=issue&itemId=82975304)

**Comment by g4rkk** [comment]
コメントありがとうございます、
４ポイント以上のカード細分化しました。
ご確認お願いいたします。

**Comment by Tsuchiya2** [comment]
![image](https://github.com/user-attachments/assets/54f16d0e-3afb-41ca-969b-575adefe001f)

カリキュラムの見本projectsにあるように1週間単位でスケジュールが分かるようにしてください。

**Comment by g4rkk** [comment]
コメントありがとうございます。
プロコースなので卒業日は10/19になっておりますて、
MVPリリースまで毎日長時間作業するつもりですので日単位でスケジュールを分けました。
ご確認どうぞよろしくお願いいたします。

**Comment by Tsuchiya2** [comment]
概ね良いかと思います。LGTMです。
